fix: show_hooks didn't work anymore
helpers.py had to move to be installed properly.  Before that, it failed
with:

```
% show_hooks --help
Traceback (most recent call last):
  File "/usr/local/virtualenvs/repo-tools/bin/show_hooks", line 5, in <module>
    from edx_repo_tools.dev.show_hooks import main
  File "/usr/local/virtualenvs/repo-tools/lib/python3.8/site-packages/edx_repo_tools/dev/show_hooks.py", line 10, in <module>
    from helpers import paginated_get
ModuleNotFoundError: No module named 'helpers'
```